### ISSUE TITLE
Origin

### ISSUE THREAD

**Issue by rhattersley** [SciTools/iris-grib#1]
Created from SciTools/iris using https://gist.github.com/rhattersley/406fc67f540fb7a239b8a88672b529e8

**Comment by pelson** [comment]
A ruby script eh? Curious 🔍 

Anyway. Thanks for making that public. 👍

**Comment by rhattersley** [comment]
We might need to run it again once @pp-mo has [patched up the grib interface in iris](https://github.com/SciTools/iris/pull/2011).

**Comment by rhattersley** [comment]
Re-ran the notebook against https://github.com/SciTools/iris/commit/34c08894b2d69c0938cac6a4fc111986665e9696, resulting in 3ad651e70ae811858a98cae27105231f9c75f408.
