### ISSUE TITLE
Iris-grib saver doesn't save attributes

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/iris-grib#115]
The grib saver used by iris (iris-grib, grib_api) does not save any attributes of cubes, with the exception of the attribute: 'centre = Met Office', which can then not be loaded back in.

**Comment by pelson** [comment]
There is no place for a fileformat like GRIB and PP to save general attributes. It is a limitation of the fileformat, not iris-grib itself. The truth is that saving to anything but a general-purpose like HDF/NetCDF is going to be lossy at some point (lossy in that it loses metadata).

Is the proposal that we document this somewhere? Would you be willing to put forward a straw-man as to where this should live?

**Comment by pp-mo** [comment]
Closed as I think @pelson view is right : there ***is*** no place to store arbitrary additional info
