### ISSUE TITLE
GRIB level save accuracy

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris-grib#117]
Ensure we can save non-integer levels (such as `level=1.5m`) to GRIB.

Note: ported here from Iris - see https://github.com/SciTools/iris/issues/675 for the original issue.

**Comment by pp-mo** [comment]
I chased this down and it is a non-issue.
It was a sort-of bug, but it relates to a "computed key", so we no longer use this at all.

Ref : https://software.ecmwf.int/issues/browse/SUP-588
"""
Xavier Abellan added a comment - 15/Aug/13 2:47 PM
Hi Byron,

The "level" key is not part of the GRIB standard, but it is an "artificial" key that grib_api provides for convenience, and that is computed based on the encoded values of two keys: scaleFactorOfFirstFixedSurface and scaledValueOfFirstFixedSurface:

http://www.ecmwf.int/publications/manuals/d/gribapi/fm92/grib2/detail/templates/4/0/

This computed "level" key is defined as a long value, not real. Changing this to a real would have important side effects, so the solution to this is not trivial. However You can set this two variables to the proper values (factor=2,value=1), and the level will be encoded correctly according to the standard. Grib_api will not be able to display the real value, but given that the encoded keys are correct, you could compute it yourself getting those two keys and doing the math.

I have raised a feature request anyway for this to be at least studied for future releases.

Regards,

Xavi

========
Daniel Varela Santoalla added a comment - 21/Jul/14 9:39 AM
Hi Patrick

This bug has finally been solved and the fix should be included from version 1.13.0 onwards.

Regards
Daniel
"""
