### ISSUE TITLE
Outstanding technical debt

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris-grib#120]
A grab-bag of known issues we'd like to get round to "some time"
**PLEASE ADD ANY YOU LIKE...**

  * #56 GRIB1 support is still using the old "non-strict" grib handler code
    * **fix**: rewrite grib1 loading using `iris_grib.message.GribMessage` instead
    * **legacy cost:** clarity of main code structure; dread to maintain this (though little need has arisen)
  * #119 all save rules are written in terms of the gribapi API, unlike the load rules
    * **fix:** 
      * extend `GribMessage` to add 'create from template' and 'write to file'.
      * rewrite existing save rules in terms of `GribMessage`, and rearrange sectionally (like load rules)
    * **legacy cost**: 
      * different from load rules means more to learn, hard to read
      * testing is especially more complicated

**Comment by pelson** [comment]
@pp-mo - now that the issue has run its course, please turn these into separate issues (feel free to add a label for each if it is helpful)

**Comment by pp-mo** [comment]
I've created a label for this now instead.
Also assigned a few things to 0.15.x milestone, in hopes ...
