### ISSUE TITLE
Statistical processing period being set wrong on save?

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris-grib#132]
I think iris-grib might be setting value of the `lengthOfTimeRange` key incorrectly when saving cubes with a  statistic (cell method) over time. According to the GRIB spec, the definition of this key (as used in PDT4.8, PDT4.10 and PDT4.11) is:

> Length of the time range over which statistical processing is done, in units defined by the previous octet

To me, this sounds like the interval of the cell method. For example, in the following case, I'd have expected this key to be set to one hour:

```
Cell methods:
    mean: time (1 hour)
```

Instead, the value of this key is currently being set as the difference between lower and upper bound of the cube's time coordinate point:

https://github.com/SciTools/iris-grib/blob/6901365c2b6d6d0311531f309ed74580c7d40b06/iris_grib/_save_rules.py#L1006-L1012

I'd appreciate others' input here – is `iris-grib` doing the right thing currently, or do we need to correct the above code?

**Comment by ESadek-MO** [comment]
Although this is a relevant question, there's no clear way to progress unless someone raises this; @SciTools/peloton have decided to close for now.
