### ISSUE TITLE
Time averaged fields parsed incorrectly for ARPEGE

### ISSUE THREAD

**Issue by marfel** [SciTools/iris-grib#139]
Hi,

I am currently working with data from the ARPEGE model (downloadable from here: https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=130&id_rubrique=51).

Several of their fields are cumulative or in some other way time averaged, but `iris-grib` does not seem to be able to interpret them correctly. I don't know whether the files are not written according to the standard, or if it's a case that just hasn't occurred yet, but the following patch seems to do the trick:

```diff
--- a/iris_grib/_load_convert.py
+++ b/iris_grib/_load_convert.py
@@ -1661,6 +1661,11 @@ def statistical_forecast_period_coord(section, frt_coord):
 
     # Get the period end time (as a timedelta relative to the frt).
     end_time_delta = end_time - frt_point
+    if (end_time_delta.total_seconds() <= 0) and ('lengthOfTimeRange' in section.keys()):
+        # apparently the end time is not set correctly, replace it
+        # with a different key (needed e.g. for ARPEGE model)
+        time_range_seconds = forecast_units.convert(section['lengthOfTimeRange'], 'seconds')
+        end_time_delta = timedelta(seconds=time_range_seconds) + start_time_delta
 
     # Get the middle of the period (as a timedelta relative to the frt).
     # Note: timedelta division in 2.7 is odd. Even though we request integer
```

BTW, there are also a number of parameters which `iris-grib` does not recognize. I manually hacked the `GRIB2_TO_CF` list and the standard names check to make it work, but maybe someone who knows how the translation lists are generated could implement this properly?

**Comment by pp-mo** [comment]
@SciTools/peloton this is looking very old now, but it doesn't seem to be a priority .
I;m going to pre-emotively close this : if still important @marfel please re-open !
