### ISSUE TITLE
Installing iris-grib free version and iris=1.13 in the same environment

### ISSUE THREAD

**Issue by valeriupredoi** [SciTools/iris-grib#144]
Hey guys @bjlittle @corinnebosley here's one for you after the bank holiday weekend :grin: 

Installing `iris-grib` and `iris=1.13` in a conda environment is not working unless `iris-grib` is restricted to an old version. See e.g.:
```
---
name: cdds_free
channels:
  - conda-forge

dependencies:
  - iris=1.13
  - iris-grib
```

This will install `iris=1.13` and `iris-grib=0.12` and the env will be created no problemo, but the env is not functional since `iris-grib` wants `iris._lazy_data` which is available only in iris>=2.

Just a heads up you guys need to tweak a bit the conda dependencies file for iris-grib :beer:

**Comment by bjlittle** [comment]
@valeriupredoi Nice one, thanks for the heads-up! :+1:

**Comment by bjlittle** [comment]
@valeriupredoi I had a quite peek into this, and unfortunately your going to have to be more explicit about the version of `iris-grib` that you want given the version of `iris` that you also want to install.

i.e. the workaround is to state:
```
dependencies:
    - iris=1.13
    - iris-grib<0.11
```
Noted, that the **old** dependencies of `iris-grib` are too loose (our doing) hence why you can get into a weird state where `iris` and `iris-grib` are out of alignment, but we're not going to go backwards to tighten up the dependencies for `iris-grib`.... that horse has bolted (so to speak).

Are you happy with just pinning the version of `iris-grib` back to `<0.11` instead?

**Comment by valeriupredoi** [comment]
@bjlittle Bill man, sure, let's not revive a dead horse :grin: I can do the pinning no problemo; frankly, I am a bit embarrassed I have to bring such an old deps issue up, but the CDDS folk are using Python2 only and iris 1.13, nothing I can do about it. Feel free to close this issue if there's nothing else to be done on your side :beer:
