### ISSUE TITLE
Fix level indexing in hybrid coords

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris-grib#150]
Revert #106 !
I think this change was a misunderstanding : the test data does not show clearly that these were the wrong numbers -- but other (real) data since encountered does.

( N.B. the actual Grib spec is really vague on this, hence the interpretation depended on what I found in actual files ! )

**Comment by trexfeathers** [comment]
Internal tracking number AVD-1314 (for internal examples)

**Comment by lbdreyer** [comment]
We are unlikely to do a v0.14.2 release so I'm going to put this in the v0.15.0 release instead
