### ISSUE TITLE
Update iris-grib docs

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris-grib#163]
The docs (https://iris-grib.readthedocs.io/en/latest/ref/release_notes.html) have not been updated since 0.13.0.

It is suggested that the builds are failing due to the jobs running out of resources (readthedocs builds are limited to 1GB of memory and 15 minutes time see https://docs.readthedocs.io/en/stable/builds.html#build-process) 

A possible solution that has been suggested would be to use pip to install iris rather than conda, apparently this saves some space?

**Comment by pp-mo** [comment]
Checked today, and I think it may be working again now.
We need to keep the version strings in the docs files up-to-date though !

**Comment by pp-mo** [comment]
> I think it may be working again now.

Except.. RTD "stable" may be  to be "stuck" due to hiatus : that seemed to persist even though I manually rebuilt v0.14./01 and  v0.15.0/1.

**Comment by pp-mo** [comment]
**LATEST** as above, "latest" is wrong.

I think the build+push will work, and 'latest' will fix itself, when we cut the next release.

**Comment by pp-mo** [comment]
I think this is ok, it is working for now.
