### ISSUE TITLE
GRIB2_TO_CF is unused

### ISSUE THREAD

**Issue by bblay** [SciTools/iris-grib#236]
[GRIB2_TO_CF](https://github.com/SciTools/iris/blame/master/lib/iris/fileformats/grib/_grib_cf_map.py#L96) is unused.
It was probably supposed to be used in [_make_grib2_to_cf_table, line 199](https://github.com/SciTools/iris/blob/master/lib/iris/fileformats/grib/grib_phenom_translation.py#L199) (@pp-mo, is that correct?).

_CF_TO_GRIB1Local_ and _CFConstrained_TO_GRIB1Local_ are also unused.

Apologies, it was me who merged SciTools/iris#482. I will be more cautious when pressed for a hurried merge.

**Comment by rcomer** [comment]
Transferred old issue from Iris.  The variable still exists, but I haven’t checked whether it’s still unused.
https://github.com/SciTools/iris-grib/blob/ad6c676eba036fb07cdaa20960450dc6e13407ed/iris_grib/_grib_cf_map.py#L59

**Comment by rcomer** [comment]
Ah, here ‘tis
https://github.com/SciTools/iris-grib/blob/ad6c676eba036fb07cdaa20960450dc6e13407ed/iris_grib/grib_phenom_translation.py#L187
