### ISSUE TITLE
Fix the assumed spherical earth radius for GRIB1 data.

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris-grib#241]
Possibly, this has always been wrong.
The gribapi has recently changed on that assumption : see [this comment](https://github.com/SciTools/iris-grib/pull/240#issuecomment-762972135).

As it's a breaking change, and come quite late, we included [a fix to preserve the 'old' behaviour](https://github.com/SciTools/iris-grib/pull/240/commits/6474926d86be4191864e21e9aa88ec1d9b2dc396) for release v0.16,.

It might in fact be "more correct" to use the gribapi-provided default 'radiusOfTheEarth' parameter,
so **this needs re-considering.**

**Comment by lbdreyer** [comment]
A short summary so far:

`shapeOfTheEarth` is a GRIB2 concept which has been implemented in GRIB1 although there is an inconsistency.

In GRIB1 the default value of `shapeOfTheEarth` is 6 which corresponds to a spherical earth of radius 6367470
However, in GRIB2 `shapeOfTheEarth` of 6 is said to mean a spherical earth of radius 6371229, and `shapeOfTheEarth` 0 means a spherical earth of radius 6367470.

This was inconsistency was raised in https://jira.ecmwf.int/browse/ECC-811. The solution is that ECMWF have hidden the key and tell users not to access `shapeOfTheEarth` in GRIB1 and instead to use the `radius` key as @pp-mo suggests.
