### ISSUE TITLE
Make iris-grib flake8 compliant

### ISSUE THREAD

**Issue by jamesp** [SciTools/iris-grib#252]
`iris-grib` currently fails to pass `flake8`.

**Comment by jamesp** [comment]
Once this issue and #251 are addressed, CI flake and black checking can be enabled by uncommenting the `lint_task` in `.cirrus.yml`

**Comment by TomDufall** [comment]
I'm currently messing about with this to explore the codebase more, hopefully leading into looking at [pytest migration](https://github.com/SciTools/iris-grib/issues/253) as a personal project/CPD (so, no guarantee I won't lose interest.) [WIP is here](https://github.com/TomDufall/iris-grib/tree/flake8) and shouldn't take much longer to finish.

**Comment by TomDufall** [comment]
Merged and passing on the 0.17.x branch!
