### ISSUE TITLE
Testing against Iris release and Iris master branch

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris-grib#277]
In https://github.com/SciTools/iris-grib/pull/231, we introduced testing against both a release of iris-grib and the latest iris master branch.

There has been some concern about the complexity introduced by handling both cases (see #272 for more discussion on this, e.g. [this comment](https://github.com/SciTools/iris-grib/pull/272#issuecomment-856635033)) 

We could consider alternative solutions to how we ensure iris and iris-grib don't diverge to much

**Comment by bjlittle** [comment]
@pp-mo This was delivered by #415, which tests against the latest `iris` available from `conda-forge` and from the latest source from the `main` branch of `iris`.
