### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris-grib#280]
See https://github.com/github/renaming

As we have already started making this change to other repos in the SciTools (see [iris discussion](https://github.com/SciTools/iris/discussions/4186), [nc-time-axis](https://github.com/SciTools/nc-time-axis/branches))

If there are no objections, I'd like to push ahead by the end of next week

**Comment by lbdreyer** [comment]
@pp-mo has kindly renamed the branch, so this can be closed.

**Comment by trexfeathers** [comment]
Note that [README.md](https://raw.githubusercontent.com/SciTools/iris-grib/99d43447444e46f1a909d665ea7b4a89fb5c949d/README.rst) has several badges that still point to `master`.
