### ISSUE TITLE
0.17.1 on PyPI?

### ISSUE THREAD

**Issue by MHBalsmeier** [SciTools/iris-grib#284]
Hello everyone,

would it be possible to publish 0.17.1 on PyPI? #273 keeps showing up for those who install with pip from PyPI, because there 0.17.0 is the latest version, which is basically unusable on Ubuntu due to this bug ...
Would be greatly appreciated.

Thanks.

**Comment by lbdreyer** [comment]
Thanks for the nudge @MHBalsmeier !

I have now uploaded 0.17.1 to PyPI: https://pypi.org/project/iris-grib/0.17.1/

Let us know if you have any issues!

**Comment by MHBalsmeier** [comment]
Thanks, everything works fine (at least in my case), I will close this.
