### ISSUE TITLE
iris-grib pre-commit-config

### ISSUE THREAD

**Issue by HGWright** [SciTools/iris-grib#388]
https://learn.scientific-python.org/development/guides/repo-review/?repo=scitools%2Firis-grib

**and enable pre-commit CI on the project PRs,** , please !

**Comment by trexfeathers** [comment]
> **and enable pre-commit CI on the project PRs,** , please !

![image](https://github.com/SciTools/iris-grib/assets/40734014/e764b440-af23-4948-8820-4d78a2da8a38)

✔
