### ISSUE TITLE
Write GRIB1 loading tests to modern standards

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris-grib#488]
Iris-grib has been loading GRIB1 for years, so to the best of our knowledge it is loading things correctly in our users' eyes. **Write a series of tests that thoroughly assert the current behaviour as the desired behaviour, by examining the loaded `Cube`s**. This is the principle as Assert-CML, if we wanted to go that direction.

This work is required to support #56 - we can make sweeping refactors and know that we have not changed behaviour.

### Files to check

```
$ cd ...git/iris-test-data/test_data/GRIB
$ find . -iname "*.grib1"
./lambert/lambert.grib1
./rotated_uk/uk_wrongparam.grib1
./reduced/reduced_ll_missing.grib1
./reduced/reduced_ll.grib1
./shape_of_earth/global.grib1
./time_processed/time_bound.grib1
./gaussian/regular_gg.grib1
```

### Possible implementations

- `AssertCML`
- `Cube` equality against saved NetCDF `Cube`s
- Many specific `assert`s

**Comment by trexfeathers** [comment]
Contrary to our original discussion, I think this is **already done**. @pp-mo can you check my logic?

- [x] `lambert/lambert.grib1`
  https://github.com/SciTools/iris-grib/blob/8f1299d5b02d6c1bd830c77753014c2e15025698/src/iris_grib/tests/integration/load_convert/test_sample_file_loads.py#L88-L90
- [x] `rotated_uk/uk_wrongparam.grib1`
  https://github.com/SciTools/iris-grib/blob/8f1299d5b02d6c1bd830c77753014c2e15025698/src/iris_grib/tests/integration/load_convert/test_sample_file_loads.py#L24-L28
- [x] `reduced/reduced_ll_missing.grib1`
  Testing deliberately stopped in SciTools/iris@af01efb
- [x] `reduced/reduced_ll.grib1`
  https://github.com/SciTools/iris-grib/blob/8f1299d5b02d6c1bd830c77753014c2e15025698/src/iris_grib/tests/integration/load_convert/test_sample_file_loads.py#L108-L110
- [x] `shape_of_earth/global.grib1`
  https://github.com/SciTools/iris-grib/blob/8f1299d5b02d6c1bd830c77753014c2e15025698/src/iris_grib/tests/integration/load_convert/test_sample_file_loads.py#L194-L197
- [x] `time_processed/time_bound.grib1`
  https://github.com/SciTools/iris-grib/blob/8f1299d5b02d6c1bd830c77753014c2e15025698/src/iris_grib/tests/integration/load_convert/test_sample_file_loads.py#L30-L34
- [x] `gaussian/regular_gg.grib1`
  https://github.com/SciTools/iris-grib/blob/8f1299d5b02d6c1bd830c77753014c2e15025698/src/iris_grib/tests/integration/load_convert/test_sample_file_loads.py#L96-L100

**Comment by pp-mo** [comment]
> Contrary to our original discussion, I think this is **already done**. @pp-mo can you check my logic?

Yes I see what you mean.
Just a couple of possible missing points I think ...

I found there is at least 1 more , untested grib1 file [`test_data/GRIB/grib1_second_order_packing/GRIB_00008_FRANX01`](https://github.com/SciTools/iris-test-data/blob/master/test_data/GRIB/grib1_second_order_packing/GRIB_00008_FRANX01)
I missed that in the above suggested search `find ... -iname "*.grib1"`, 
but it is found by  `find ... -iname "*grib1*"` .
Iris can load this file OK it seems, it contains some kind of packed data array. So I guess **_a CML check for that is worth having_** ?

Also..
> * [x]  `reduced/reduced_ll_missing.grib1`
>   Testing deliberately stopped in [SciTools/iris@af01efb](https://github.com/SciTools/iris/commit/af01efb)

This one is interesting.  It now gives an error on loading, I just spent ages trying to work out when it stopped working.
I think we were ignoring tests for a while in the transition from iris.fileformats.grib to iris_grib, and it happened in there somewhere.  Presumably since this has not worked for **_so_** long, we don't need to worry about it.

**Comment by pp-mo** [comment]
P.S. for completeness, I will also go looking for any other GRIB1 data we may have in iris-test-data, which is not apparent from the file names.
I'll get back to you on that one ...

**Comment by pp-mo** [comment]
> P.S. for completeness, I will also go looking for any other GRIB1 data we may have in iris-test-data, which is not apparent from the file names. I'll get back to you on that one ...

OK I think there **_are_** a couple more loadable files in the iris-test-data which are GRIB1 format, and seem worth checking for :
  * `test_data/GRIB/polar_stereo/ST4.2013052210.01h`
  * `test_data/GRIB/bulletin/41bytes.grib`

**Comment by trexfeathers** [comment]
> Also..
> 
> > * [x]   `reduced/reduced_ll_missing.grib1`
> >   Testing deliberately stopped in [SciTools/iris@af01efb](https://github.com/SciTools/iris/commit/af01efb)
> 
> This one is interesting. It now gives an error on loading, I just spent ages trying to work out when it stopped working. I think we were ignoring tests for a while in the transition from iris.fileformats.grib to iris_grib, and it happened in there somewhere. Presumably since this has not worked for **_so_** long, we don't need to worry about it.

You introduced the skipping of this test around a year before it was removed entirely, as part of SciTools/iris#2085 - it wasn't being skipped in its previous location, but the skip was present in the file you added.
