### ISSUE TITLE
Migrate to eccodes

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris-grib#58]
This is presumably the future, and should replace "gribapi".
https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home

N.B. latest declaration says this is currently "in beta", so maybe not quite ready

**Comment by dkillick** [comment]
Thanks @pp-mo -- I guess that if it's in beta we shouldn't be bringing it in as our primary grib translator. We could however put together a beta version of our own that utilises `eccodes` to test its functionality and to perhaps be ahead of the curve when eccodes gets released properly.

**Comment by andreas-h** [comment]
According to https://software.ecmwf.int/wiki/display/ECC:

> ecCodes version 2.0.0
> This is the first full (Production-ready) release of ecCodes.

**Comment by pelson** [comment]
xref: https://github.com/SciTools/iris/pull/2607

**Comment by pelson** [comment]
Merged in #92.
