### ISSUE TITLE
Enable web documentation

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris-grib#60]
Following #55, we need to enable docs building on this repo.

I think that means a bit more work with readthedocs, to sort out an scitools organisation account and possibly to get to build docs for tagged release versions.
It will then maintain docs for different versions with a dropdown control (and a 'latest' concept), which if you care about it seems to be a key benefit from readthedocs.

**Comment by pelson** [comment]
Looks like this got done?

**Comment by pp-mo** [comment]
Yes, and it seems up-to-date, so we can close.
