### ISSUE TITLE
FF - GRIB2 conversion failure (Iris test data file)

### ISSUE THREAD

**Issue by DPeterK** [SciTools/iris-grib#61]
Trying to convert the `n48-multi-field` FF from the Iris test data repo fails:

``` python
cubes = iris.load('n48-multi-field')
>>> iris.save(cubes, test.grib2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'test' is not defined
>>> iris.save(cubes, 'test.grib2')
GRIB_API ERROR   :  Key "forecastTime": Trying to encode a negative value of -3 for key of type unsigned

Traceback (most recent call last):
  ..
  File "/.../gribapi/__init__.py", line 143, in GRIB_CHECK
    raise GribInternalError(errid)
gribapi.GribInternalError: Encoding invalid
```

**Comment by dkillick** [comment]
Perhaps unsurprisingly, we get the same errors for the test data repo files `n48_multi_field.ieee32` and `n48_multi_field_table_count` as well.

**Comment by dkillick** [comment]
In fact, we can't translate _any_ of the Iris Test Data FieldsFiles to GRIB2:

**`ancillary/qrparm.mask`:**
```python
Traceback (most recent call last):
  ...
  File "/.../iris_grib/_save_rules.py", line 1101, in gribbability_check
    raise iris.exceptions.TranslationError("time coord not found")
iris.exceptions.TranslationError: time coord not found
```

**`lbc/small_lbc`:**
```python
/.../iris_grib/_save_rules.py:528: UserWarning: Unable to determine Grib2 parameter code for cube.
discipline, parameterCategory and parameterNumber have been set to "missing".
  warnings.warn('Unable to determine Grib2 parameter code for cube.\n'
Traceback (most recent call last):
  ...
  File "/.../iris_grib/_save_rules.py", line 678, in set_fixed_surfaces
    'are not recognised or handled.'.format(v_coords_str))
iris.exceptions.TranslationError: The vertical-axis coordinate(s) ('level_height' ,'model_level_number') are not recognised or handled.
```

**`structured/small`:**
```python
Traceback (most recent call last):
  ...
  File "/.../iris_grib/_save_rules.py", line 678, in set_fixed_surfaces
    'are not recognised or handled.'.format(v_coords_str))
iris.exceptions.TranslationError: The vertical-axis coordinate(s) ('level_height' ,'model_level_number') are not recognised or handled.
```

**Comment by pp-mo** [comment]
I've looked into this in detail now, testing all files in the FF subsection of the test data.
There are a lot of errors, because a lot of this data has features we don't support for GRIB save.
However, I'm happy that it is behaving exactly the same in iris-grib as it does with the old embedded 

See: https://gist.github.com/pp-mo/f021a95d002837709c292273090f4b9f
Note: in all cases, old and new save either both succeed, or both fail with an identical error.

**Comment by RPrudden** [comment]
Did you ever get to the bottom of this? I'm having the same problem when I try to save a cube to grib2

`TranslationError: The vertical-axis coordinate(s) ('model_level_number') are not recognised or handled.`

**Comment by pp-mo** [comment]
Closing as really old.
Though the problems probably still exist, I think we can only progress with specific proposals to fix specific encoding problems.
