### ISSUE TITLE
two phenomena with the  same Grib2 parameter

### ISSUE THREAD

**Issue by hai-peng-wang** [SciTools/iris-grib#64]
Hi there,

While I'm trying to handle each Grib2 message with iris-grib, I found there two messages with identical Grib2 parameter but discribing different phenomenon. How could I handle this in terms of putting the G2Param codes in the _grib_cf_map.py.

I attached the details of these two message below:

1) Variable "Visibility_height_above_ground"
 
float Visibility_height_above_ground(time=1, height_above_ground1=1, lat=769, lon=1024);
  :long_name = "Visibility @ Specified height level above ground";
  :units = "m";
  :description = "Visibility";
  :missing_value = NaNf; // float
  :grid_mapping = "LatLon_Projection";
  :coordinates = "reftime time height_above_ground1 lat lon ";
  :Grib_Variable_Id = "VAR_0-19-0_L103";
  :Grib2_Parameter = 0, 19, 0; // int
  :Grib2_Parameter_Discipline = "Meteorological products";
  :Grib2_Parameter_Category = "Physical atmospheric properties";
  :Grib2_Parameter_Name = "Visibility";
  :Grib2_Level_Type = "Specified height level above ground";
  :Grib2_Generating_Process_Type = "Analysis";

2) Variable "Visibility_height_above_ground_probability_below_5000"
 
float Visibility_height_above_ground_probability_below_5000(time=1, height_above_ground1=1, lat=769, lon=1024);
  :long_name = "Probability Visibility below_5000 m @ Specified height level above ground";
  :units = "%";
  :description = "Visibility";
  :missing_value = NaNf; // float
  :grid_mapping = "LatLon_Projection";
  :coordinates = "reftime time height_above_ground1 lat lon ";
  :Grib_Variable_Id = "VAR_0-19-0_L103_Prob_below_5000";
  :Grib2_Parameter = 0, 19, 0; // int
  :Grib2_Parameter_Discipline = "Meteorological products";
  :Grib2_Parameter_Category = "Physical atmospheric properties";
  :Grib2_Parameter_Name = "Visibility";
  :Grib2_Level_Type = "Specified height level above ground";
  :Grib2_Probability_Type = 0; // int
  :Grib2_Probability_Name = "below_5000";
  :Grib2_Generating_Process_Type = "Analysis";

Thanks!

Regards
Haipeng

**Comment by marqh** [comment]
Hello @hai-peng-wang 

how are these two messages encoded?  Are they using the same Product Definition Template or different ones?

At present the mapping between GRIB2 parameter codes and CFnames+units is limited to only this mapping.  It takes one GRIB collection (discipline, category number) and links to one and only one CFName+unit

There may be some differentiation available, for different product definition templates, but encoding parameterised probabilities such as 
`Probability Visibility below_5000 m @ Specified height level above ground`
is not at all well supported by CF, which Iris uses for metadata, so it is not going to be defined explicitly in Iris.  you can always use a bespoke long name to differentiate, I don't think much more is available

is this helpful?  please feel free to ask more questions

mark

**Comment by zak-k** [comment]
This problem also occurs in a more commonplace context: both air_pressure and surface_air_pressure are represeted by the GRIB2 parameter (0,3,0) but with a different typeOfFirstFixedSurface.  This is unlike GRIB1, where these variables have different parameter codes.

As a result, a (0,3,0) surface field is read in as air_pressure rather than surface_air_pressure and is thus unable to be used when constructing a HybridPressureFactory.

**Comment by hai-peng-wang** [comment]
Sorry for a late reply to follow the issue. Mark, you are right that using a bespoke long name is what I can do currently to handle such situations and thanks for pointing out this.

Best regards
Haipeng

**Comment by pp-mo** [comment]
Reviewing/tidying some old issues.
I think this is answered, though the problem remains (it seems it will always be with us)
@hai-peng-wang @zak-k Please re-raise or re-open if wanted.
