### ISSUE TITLE
Python3 problems

### ISSUE THREAD

**Issue by andreas-h** [SciTools/iris-grib#74]
I'm having a problem importing iris_grib in Python3:

    >>> import iris_grib
    [...]
    No module named 'gribapi_swig'

However, installing grib_api with --enable-python didn't complain ...

Any ideas what might be the issue?

**Comment by marqh** [comment]
Hi @andreas-h 

i'm working on getting getting GRIB working with ECCodes (#58) at the moment

until then, there's no Python3 support I'm afraid.  the legacy grib_api is not Python3 compatible

please leave this issue open and I'll update you with progress

mark

**Comment by pelson** [comment]
Just to update: we now have an iris-grib that supports eccodes. Unfortunately, eccodes doesn't *yet*, support python 3. The best place I know  to track the progress of this is in https://github.com/conda-forge/python-eccodes-feedstock/issues/3.

We do not see any blockers in python3 support once eccodes is available for python 3.

**Comment by pelson** [comment]
P.S. The work that got eccodes in was mostly done by @marqh and completed in #92.

**Comment by xzenggit** [comment]
Got the same error while using Python3 and iris-grib. Hope iris-grib can support Python3 soon. Thank you.

**Comment by bjlittle** [comment]
@xzenggit Thanks. The ECMWF are hoping to provision Python3 ecCodes support by the end of this year! Once they do, `iris-grib` will be able to finally work in Python3 😄

**Comment by lrntct** [comment]
Hi,
The python 3 compatibility of eccodes seems to be [fixed](https://github.com/conda-forge/python-eccodes-feedstock/issues/3).
It would be nice if we could read GRIB with iris in python 3.

**Comment by pp-mo** [comment]
Just reviewing some old issues.
This ought to be fixed now.

@andreas-h @xzenggit @lrntct do you have anything to add here ?
Otherwise will close
