### ISSUE TITLE
gribapi or grib_api?

### ISSUE THREAD

**Issue by matteodefelice** [SciTools/iris-grib#83]
I'have compiled and installed GRIB API but the python package installed is named `grib_api` while `iris-grib` looks for `gribapi`. What am I supposed to do?

**Comment by pelson** [comment]
Hi @matteodefelice. Sorry nobody was able to get back to you sooner. We are looking for a ``gribapi`` package as built by conda-forge: https://github.com/conda-forge/python-ecmwf_grib-feedstock/blob/master/recipe/meta.yaml

Specifically, it is the ECMWF's GRIB API (and subsequently their eccodes library).

Which GRIB API are you using?
