### ISSUE TITLE
Tables incomplete?

### ISSUE THREAD

**Issue by marfel** [SciTools/iris-grib#84]
Hi,
we are working a lot with different NWP models, and I was hoping `iris-grib` would be the glue to join the NetCDF and GRIB worlds. I already have some homebrew classes to deal with this mess, but of course it would be much more attractive to leverage the power of `iris` for this job. However, after installing from `conda`

```
ecmwf_grib                1.23.1                        0    conda-forge
iris                      1.13.0                   py27_1    conda-forge
iris-grib                 0.10.1                   py27_0    conda-forge
python-ecmwf_grib         1.23.1                   py27_0    conda-forge
```

I still get a lot of unknown fields for most of our GRIB data (examples for GFS-4, ECMWF and Environment Canada GDPS appended). These fields check out fine when I run e.g. `grib_ls` in the command line, where `grib_info` also points to the exact conda environment I run the Python code from:

```
grib_api Version 1.23.1
Default definition files path is used: /user/martin/.conda/envs/dev/share/grib_api/definitions
```

Can anyone explain this effect? I'm quite motivated to help getting this thing to fly, but I would appreciate someone pointing me in the right direction first.

Another (probably related?) issue is that for e.g. the GFS-4 in my example, I get like 10 cubes of `y_wind` having the exact same metadata. In reality, they differ in `levelType`. Can I somehow tell the load function to attach the `levelType` (and/or any other parameters I'm interested in) to the cube as a meta-parameter? Or is the philosophy here to fiddle with the `GribMessages` on a low level and then call `load_pairs_from_fields`?

[iris_grib_issues.txt](https://github.com/SciTools/iris-grib/files/1346529/iris_grib_issues.txt)

Best Regards,
Martin

**Comment by JoaoGF21** [comment]
> Hi,
> we are working a lot with different NWP models, and I was hoping `iris-grib` would be the glue to join the NetCDF and GRIB worlds. I already have some homebrew classes to deal with this mess, but of course it would be much more attractive to leverage the power of `iris` for this job. However, after installing from `conda`
> 
> ```
> ecmwf_grib                1.23.1                        0    conda-forge
> iris                      1.13.0                   py27_1    conda-forge
> iris-grib                 0.10.1                   py27_0    conda-forge
> python-ecmwf_grib         1.23.1                   py27_0    conda-forge
> ```
> I still get a lot of unknown fields for most of our GRIB data (examples for GFS-4, ECMWF and Environment Canada GDPS appended). These fields check out fine when I run e.g. `grib_ls` in the command line, where `grib_info` also points to the exact conda environment I run the Python code from:
> 
> ```
> grib_api Version 1.23.1
> Default definition files path is used: /user/martin/.conda/envs/dev/share/grib_api/definitions
> ```
> Can anyone explain this effect? I'm quite motivated to help getting this thing to fly, but I would appreciate someone pointing me in the right direction first.
> 
> Another (probably related?) issue is that for e.g. the GFS-4 in my example, I get like 10 cubes of `y_wind` having the exact same metadata. In reality, they differ in `levelType`. Can I somehow tell the load function to attach the `levelType` (and/or any other parameters I'm interested in) to the cube as a meta-parameter? Or is the philosophy here to fiddle with the `GribMessages` on a low level and then call `load_pairs_from_fields`?
> 
> [iris_grib_issues.txt](https://github.com/SciTools/iris-grib/files/1346529/iris_grib_issues.txt)
> 
> Best Regards,
> Martin

Hi, Martin,

I am facing the same issues trying to use iris 2.2 to read GFS 0.25.
Did you find a solution?

Thank you in advance.

Best Regards,

Joao Gabriel

**Comment by marfel** [comment]
Hi Joao,

sadly, since there was no response to my cry for help, I put the issue aside for now and stuck to my old code. The problem remains, however. Also, since `xarray` seems to be taking root in the met community and the conversion to/from `iris` is simple, for me that would be one more reason to try migrating my stuff to `iris`. Please let me know if you plan on working on this issue, perhaps we can pool resources.

Best,
Martin

**Comment by zklaus** [comment]
Recently, we have been facing a similar issue. It seems this is now related to the [metarelate project](http://www.metarelate.net/metOcean). @marqh, could you shed some light, maybe point to a tutorial on how to add new parameters?

**Comment by pp-mo** [comment]
@SciTools/peloton believe this is now old enough to put itself to bed.
Please re-open if you think there are still things to be addressed here.
BTW I think that https://github.com/SciTools/iris-grib/pull/318 may fix the different level-types issue ?
